# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: previous-pipeline-trigger
    source: PR-pipeline
    trigger:
      branches:
        - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: git subtree add --prefix=sub-folder https://github.com/rushig71/stunning-rotary-phone.git main --squash
  displayName: 'add subtree'
- script: git subtree pull --prefix=sub-folder https://github.com/rushig71/stunning-rotary-phone.git main --squash
  displayName: 'subtree pull'
- script: git push
  displayName: 'subtree push'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
